### ISSUE TITLE
Source Code?

### ISSUE THREAD

**Issue by shirshak55** [oxylabs/proxy-chrome-extension#1]
Proxy extensions are known for nefarious things like how lumniati or big data preys on extension developers to integrate some source code for residential proxies. 

I think with transpiling which this extension does it's hard to audit if this extension also does in the background and it also doesn't contain sourcemaps. So is it inappropriate to ask for source code for the sake of auding?

**Comment by oxyagne** [comment]
Hello!

We can assure you that our extension doesn’t turn its user into a proxy. If you like, you can verify this by watching your network traffic while the extension is running. We have better ways of acquiring residential proxies, which are both legal and ethical. 

You can read about our proxy sourcing practices here: https://oxylabs.io/Oxylabs_Residential_Proxy_Acquisition_Handbook.pdf.  

Unfortunately, we’re not in a position to share the source code of our plugin.

**Comment by shirshak55** [comment]
@oxyagne actually monitoring networking traffic generally doesn't work, because there is no way to know when my browser will be used as a proxy. For example, there can be code like this:

If(time  >= after_12){
// run it as proxy
}


The only way to verify I guess is to read the actual source code. I don't know how much JS code is obfuscated.

Also, your practices might be true today, but it only takes a change of one member to change that practice.  We have seen such incidents with many VPNs.

By the way, you don't have to release the source code anymore, as I have written proxy myself.
